/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controladores.ControladorCategorias;
import Modelos.Producto;
import java.awt.Component;

/**
 *
 * @author crixa
 */
public class PlantillaProducto extends javax.swing.JPanel {

    /**
     * Creates new form Producto
     */
    public PlantillaProducto(javax.swing.JPanel miRef,String[] categorias,Component view) {
        initComponents();
        this.refHome = miRef;
        if (categorias.length == 0) {
            comboCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"No hay categorias"}));
        }else{
            comboCategorias.setEnabled(true);
            comboCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(categorias));
        }
        this.view = view;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        btnTitulo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        spinerCantidad = new javax.swing.JSpinner();
        comboCategorias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(460, 200));
        setMinimumSize(new java.awt.Dimension(460, 200));
        setPreferredSize(new java.awt.Dimension(460, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setBackground(new java.awt.Color(102, 102, 0));
        btnEliminar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Donaciones/fondoEliminar.png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 30, 30));

        btnTitulo.setBackground(new java.awt.Color(0, 0, 0));
        btnTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnTitulo.setForeground(new java.awt.Color(255, 255, 255));
        btnTitulo.setText("Producto");
        add(btnTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(440, 170));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 170));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 60, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoría");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 15, 70, 20));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripción");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 20));

        campoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreFocusLost(evt);
            }
        });
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 170, -1));

        spinerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinerCantidad.setOpaque(false);
        jPanel1.add(spinerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 80, -1));

        comboCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCategorias.setEnabled(false);
        jPanel1.add(comboCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 10, 90, -1));

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        campoDescripcion.setMinimumSize(new java.awt.Dimension(164, 74));
        jScrollPane1.setViewportView(campoDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 350, 120));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 440, 170));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Productos/fondo.png"))); // NOI18N
        jLabel5.setMinimumSize(new java.awt.Dimension(460, 240));
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        refHome.remove(this);
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMouseExited

    private void campoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusLost
        // TODO add your handling code here:
        String txt = campoNombre.getText();
        btnTitulo.setText(txt.equals("")?"Producto":txt);
    }//GEN-LAST:event_campoNombreFocusLost


    public Producto crearProducto(){
        //Producto(String nombre,String descripcion,int cantidad,int idCategoria)
        return new Producto(campoNombre.getText(),
                            campoDescripcion.getText(),
                            Integer.parseInt(spinerCantidad.getValue().toString()),
                            ControladorCategorias.dameIdCategoria(comboCategorias.getSelectedIndex()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnTitulo;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox<String> comboCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinerCantidad;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JPanel refHome;
    private Component view;
}
