/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controladores.ControladorCategorias;
import Controladores.ControladorDetalleDonacion;
import Controladores.ControladorDonaciones;
import Controladores.ControladorDonantes;
import Controladores.ControladorInstituciones;
import Controladores.ControladorProductos;
import Modelos.Producto;
import java.awt.Component;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author crixa
 */
public class VistaRegistrarDonacion extends javax.swing.JPanel {

    /**
     * Creates new form RegistroDonante
     */
    public VistaRegistrarDonacion(javax.swing.JPanel miRef) {
        this.refHome = miRef;
        boolean error = false;
        initComponents();
        jLabel10.setVisible(false);
        if (ControladorCategorias.cargarCategorias()) {
            listaCategorias = ControladorCategorias.obtenerCategorias();
        } else {
            error = true;
            listaCategorias = null;
            JOptionPane.showMessageDialog(null, "No se pudieron cargar las categorias", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (ControladorDonantes.cargarDonantes()) {
            listaDonantes = ControladorDonantes.obtenerDonantes();
            comboDonantes.setModel(new javax.swing.DefaultComboBoxModel<>(listaDonantes));
        } else {
            error = true;
            JOptionPane.showMessageDialog(null, "No se pudieron cargar los donantes", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (ControladorInstituciones.cargarInstituciones()) {
            listaInstituciones = ControladorInstituciones.obtenerInstituciones();
            comboInstituciones.setModel(new javax.swing.DefaultComboBoxModel<>(listaInstituciones));
        }else{
            error = true;
            JOptionPane.showMessageDialog(null, "No se pudieron cargar las instituciones", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (error) {
            this.setVisible(false);
            refHome.setVisible(true);
            refHome.remove(this);
        }

        vp = jScrollPane1.getViewport().getView();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboInstituciones = new javax.swing.JComboBox<>();
        comboDonantes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelProductos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1020, 510));
        setPreferredSize(new java.awt.Dimension(1020, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 49)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Donacion");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(102, 102, 0));
        btnRegistrar.setFont(new java.awt.Font("Bahnschrift", 0, 19)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Generales/fondoBoton.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 140, 40));

        btnHome.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Generales/home.png"))); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Generales/barraNavRegistros.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Productos");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 19)); // NOI18N
        jLabel3.setText("Donante:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 19)); // NOI18N
        jLabel4.setText("Institución:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Donaciones/producto.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("<html>Registro<br>Exitoso</html>");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 110, 60));

        comboInstituciones.setBackground(new java.awt.Color(255, 153, 153));
        comboInstituciones.setMaximumRowCount(4);
        comboInstituciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cargando..." }));
        comboInstituciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(comboInstituciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 260, 30));

        comboDonantes.setBackground(new java.awt.Color(255, 153, 153));
        comboDonantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cargando..." }));
        add(comboDonantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 260, 30));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Principal");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Donaciones/fondoAñadir.png"))); // NOI18N
        btnAgregarProducto.setBorderPainted(false);
        btnAgregarProducto.setContentAreaFilled(false);
        btnAgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseExited(evt);
            }
        });
        add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 113, 50, 50));

        jScrollPane1.setToolTipText("");
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(510, 60));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(510, 60));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(510, 60));

        panelProductos.setBackground(new java.awt.Color(204, 204, 204));
        panelProductos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                panelProductosComponentRemoved(evt);
            }
        });
        panelProductos.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(panelProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 465, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        refHome.setVisible(true);
        refHome.remove(this);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        // TODO add your handling code here:
        btnRegistrar.setFont(new java.awt.Font("Bahnschrift", 0, 19));
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        // TODO add your handling code here:
        btnRegistrar.setFont(new java.awt.Font("Bahnschrift", 1, 21));
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        Component c[] = panelProductos.getComponents();
        if (c.length != 0) {
            int idDonante = ControladorDonantes.dameIdDonante(comboDonantes.getSelectedIndex());
            int idInstitucion = ControladorDonantes.dameIdDonante(comboInstituciones.getSelectedIndex());
            int idDonacion = ControladorDonaciones.agregarDonacion(idDonante, idInstitucion);
            
            int i = 0;
            Producto lista[] = new Producto[c.length];
            for (Component cc : c) {
                lista[i] = ((PlantillaProducto) cc).crearProducto();
                ControladorProductos.agregarProducto(lista[i]);
                ControladorDetalleDonacion.agregarDetalleDonacion(idDonacion,lista[i].getId());
                i++;
            }
            
            this.panelProductos.removeAll();
            this.panelProductos.repaint();
            
            jLabel10.setVisible(true);
                Timer timer = new Timer();
                TimerTask task = new TimerTask() {
                    public void run() {
                        jLabel10.setVisible(false);
                        timer.cancel();
                    }
                };
                timer.scheduleAtFixedRate(task, 2000, 1000);
        } else {
            JOptionPane.showMessageDialog(null, "No hay productos agreados", "Error-No hay productos", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseClicked
        // TODO add your handling code here:
        panelProductos.add(new PlantillaProducto(panelProductos, listaCategorias, vp));
        /*for (Component c : this.panelProductos.getComponents()) {
            PlantillaProducto miP = (PlantillaProducto) c;
        }*/
    }//GEN-LAST:event_btnAgregarProductoMouseClicked

    private void btnAgregarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseEntered
        // TODO add your handling code here:
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Donaciones/btnAddGrande.png")));
    }//GEN-LAST:event_btnAgregarProductoMouseEntered

    private void btnAgregarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseExited
        // TODO add your handling code here:
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Donaciones/fondoAñadir.png")));
    }//GEN-LAST:event_btnAgregarProductoMouseExited

    private void panelProductosComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_panelProductosComponentRemoved
        // TODO add your handling code here:
        panelProductos.repaint();
    }//GEN-LAST:event_panelProductosComponentRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboDonantes;
    private javax.swing.JComboBox<String> comboInstituciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelProductos;
    // End of variables declaration//GEN-END:variables
    private final javax.swing.JPanel refHome;
    private final String[] listaCategorias;
    private String[] listaInstituciones;
    private String[] listaDonantes;
    private Component vp;
}
