/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;


import Controladores.SQLClass;
import javax.swing.JPanel;

/**
 *
 * @author crixa
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public VistaPrincipal() {
        this.setTitle("Donaciones San Marcos :3");
        initComponents();
        setLocationRelativeTo(null);
        SQLClass.iniciarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logoSM = new javax.swing.JLabel();
        btnRegistrarDonante = new javax.swing.JButton();
        btnRegistrarInstitucion = new javax.swing.JButton();
        btnRegistrarDonaciones = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1020, 510));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoSM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home/logosm.png"))); // NOI18N
        jPanel2.add(logoSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 190, 220));

        btnRegistrarDonante.setBackground(new java.awt.Color(255, 0, 51,0));
        btnRegistrarDonante.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnRegistrarDonante.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDonante.setText("Registrar Donante");
        btnRegistrarDonante.setBorderPainted(false);
        btnRegistrarDonante.setContentAreaFilled(false);
        btnRegistrarDonante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarDonante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarDonanteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarDonanteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarDonanteMouseExited(evt);
            }
        });
        jPanel2.add(btnRegistrarDonante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btnRegistrarInstitucion.setBackground(new java.awt.Color(255, 0, 51,0));
        btnRegistrarInstitucion.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnRegistrarInstitucion.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarInstitucion.setText("Registrar Instituciones");
        btnRegistrarInstitucion.setBorderPainted(false);
        btnRegistrarInstitucion.setContentAreaFilled(false);
        btnRegistrarInstitucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarInstitucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarInstitucionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarInstitucionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarInstitucionMouseExited(evt);
            }
        });
        jPanel2.add(btnRegistrarInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        btnRegistrarDonaciones.setBackground(new java.awt.Color(255, 0, 51,0));
        btnRegistrarDonaciones.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnRegistrarDonaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDonaciones.setText("Registrar Donaciones");
        btnRegistrarDonaciones.setBorderPainted(false);
        btnRegistrarDonaciones.setContentAreaFilled(false);
        btnRegistrarDonaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarDonaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarDonacionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarDonacionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarDonacionesMouseExited(evt);
            }
        });
        jPanel2.add(btnRegistrarDonaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 51,0));
        jButton4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Ver Datos");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home/barraNavFondo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 95));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home/logotTeleton.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home/manitos.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home/manitos.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel5.setText("SISTEMA DE DONACIONES");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("<html>\nNos sentimos orgullosos de poder contribuir <br>\na hacer más comunes las donaciones <br>\n<br>\nProyecto Base de Datos 2\n</html>");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarDonanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarDonanteMouseEntered
        // TODO add your handling code here:
        btnRegistrarDonante.setFont(new java.awt.Font("Bahnschrift", 1, 20));
    }//GEN-LAST:event_btnRegistrarDonanteMouseEntered

    private void btnRegistrarDonanteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarDonanteMouseExited
        // TODO add your handling code here:
        btnRegistrarDonante.setFont(new java.awt.Font("Bahnschrift", 0, 18));
    }//GEN-LAST:event_btnRegistrarDonanteMouseExited

    private void btnRegistrarInstitucionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarInstitucionMouseEntered
        // TODO add your handling code here:
        btnRegistrarInstitucion.setFont(new java.awt.Font("Bahnschrift", 1, 20));
    }//GEN-LAST:event_btnRegistrarInstitucionMouseEntered

    private void btnRegistrarInstitucionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarInstitucionMouseExited
        // TODO add your handling code here:
        btnRegistrarInstitucion.setFont(new java.awt.Font("Bahnschrift", 0, 18));
    }//GEN-LAST:event_btnRegistrarInstitucionMouseExited

    private void btnRegistrarDonacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarDonacionesMouseEntered
        // TODO add your handling code here:
        btnRegistrarDonaciones.setFont(new java.awt.Font("Bahnschrift", 1, 20));
    }//GEN-LAST:event_btnRegistrarDonacionesMouseEntered

    private void btnRegistrarDonacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarDonacionesMouseExited
        // TODO add your handling code here:
        btnRegistrarDonaciones.setFont(new java.awt.Font("Bahnschrift", 0, 18));
    }//GEN-LAST:event_btnRegistrarDonacionesMouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        jButton4.setFont(new java.awt.Font("Bahnschrift", 1, 20));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setFont(new java.awt.Font("Bahnschrift", 0, 18));
    }//GEN-LAST:event_jButton4MouseExited

    private void btnRegistrarDonanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarDonanteMouseClicked
        // TODO add your handling code here:
        this.jPanel2.setVisible(false);
        
            jPanelX = new VistaRegistrarDonante(jPanel2);
            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelX, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            );
    }//GEN-LAST:event_btnRegistrarDonanteMouseClicked

    private void btnRegistrarInstitucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarInstitucionMouseClicked
        // TODO add your handling code here:
        this.jPanel2.setVisible(false);
        jPanelX = new VistaRegistrarInstitucion(jPanel2);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelX, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

    }//GEN-LAST:event_btnRegistrarInstitucionMouseClicked

    private void btnRegistrarDonacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarDonacionesMouseClicked
        // TODO add your handling code here:
        this.jPanel2.setVisible(false);
        
        jPanelX = new VistaRegistrarDonacion(jPanel2);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelX, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
    }//GEN-LAST:event_btnRegistrarDonacionesMouseClicked

    public void quitaPanel(JPanel miPanel) {
        this.remove(miPanel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarDonaciones;
    private javax.swing.JButton btnRegistrarDonante;
    private javax.swing.JButton btnRegistrarInstitucion;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoSM;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JPanel jPanelX;
}
